version: '3.2'

services:
    license:
      image: docker.totvs.io/dcp/license:latest

    appserver:
      image: docker.totvs.io/dcp/appserver_x32_13:latest
      depends_on:
        - dbaccess
      ports:
        - 8080:80   # WebAPP
        - 8081:8081 # Porta para acesso TCP
        - 8084:8084 # Porta para o REST
      environment:
        - REST=true
      volumes:
        - rpo_data:/apo

    dbaccess:
      image: docker.totvs.io/dcp/dbaccess_x64:published
      depends_on:
        - database
        - license

    database:
      image: docker.totvs.io/dcp/postgres_dump:latest
      volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  rpo_data:
  db_data:
